function X = m2IV(kappa, theta, sigma, Delta, Vs, Vt)
toScale=1;
E=exp(1);
X=((4*Power(-1 + Power(E,Delta*kappa),2)*(1 + Power(E,Delta*kappa))*(Vs + Vt)* ...
((-1 + Power(E,Delta*kappa))*Power(sigma,2) + (1 + Power(E,Delta*kappa))*kappa*(Vs + Vt)) + ...
Delta^2*kappa*(Power(-1 + Power(E,Delta*kappa),2)*(1 + 6*Power(E,Delta*kappa) + Power(E,2*Delta*kappa))*Power(sigma,4) - ...
16*Power(E,Delta*kappa)*(-1 + Power(E,2*Delta*kappa))*kappa*Power(sigma,2)*(Vs + Vt) + ... 
16*Power(E,2*Delta*kappa)*Power(kappa,2)*Power(Vs + Vt,2)) + ...
2*Delta*(-1 + Power(E,Delta*kappa))*(Power(-1 + Power(E,Delta*kappa),2)*(1 + Power(E,Delta*kappa))*Power(sigma,4) + ...
2*(-1 - 3*Power(E,Delta*kappa) + 3*Power(E,2*Delta*kappa) + Power(E,3*Delta*kappa))*kappa*Power(sigma,2)*(Vs + Vt) - ...
8*Power(E,Delta*kappa)*(1 + Power(E,Delta*kappa))*Power(kappa,2)*Power(Vs + Vt,2)))/Power(-1 + Power(E,Delta*kappa),4) + ...
(4*(2*(-1 + Power(E,2*Delta*kappa))*(Vs + Vt) + Delta* ...
((-1 + Power(E,2*Delta*kappa))*Power(sigma,2) - 4*Power(E,Delta*kappa)*kappa*(Vs + Vt)))* ...
(Power(E,(Delta*kappa)/2.)*kappa*(2 + Delta*kappa + Power(E,Delta*kappa)*(-2 + Delta*kappa))*sqrt(Vs*Vt)* ...
besseli((2*kappa*theta)/Power(sigma,2),(4*Power(E,(Delta*kappa)/2.)*kappa*sqrt(Vs*Vt))/((-1 + Power(E,Delta*kappa))*Power(sigma,2)),  toScale) ...  
+  Power(E,(Delta*kappa)/2.)*kappa*(2 + Delta*kappa + Power(E,Delta*kappa)*(-2 + Delta*kappa))*sqrt(Vs*Vt)* ...
besseli(-2 + (2*kappa*theta)/Power(sigma,2), (4*Power(E,(Delta*kappa)/2.)*kappa*sqrt(Vs*Vt))/ ...
((-1 + Power(E,Delta*kappa))*Power(sigma,2)), toScale) -  ...
Power(-1 + Power(E,Delta*kappa),2)*Power(sigma,2)*  ...
besseli(-1 + (2*kappa*theta)/Power(sigma,2), (4*Power(E,(Delta*kappa)/2.)*kappa*sqrt(Vs*Vt))/ ...
((-1 + Power(E,Delta*kappa))*Power(sigma,2)),  toScale)))/ ...
(Power(-1 + Power(E,Delta*kappa),4)*besseli( -1 + (2*kappa*theta)/Power(sigma,2), ...
(4*Power(E,(Delta*kappa)/2.)*kappa*sqrt(Vs*Vt))/((-1 + Power(E,Delta*kappa))*Power(sigma,2)),  toScale)) -  ...
(4*(1 - Power(E,-(Delta*kappa)))*((2*Power(E,(Delta*kappa)/2.)*kappa*(2 + Delta*kappa + Power(E,Delta*kappa)*(-2 + Delta*kappa))* ...
Power(sigma,2)*sqrt(Vs*Vt)*(besseli((2*kappa*theta)/Power(sigma,2),  ...
(4*Power(E,(Delta*kappa)/2.)*kappa*sqrt(Vs*Vt))/((-1 + Power(E,Delta*kappa))*Power(sigma,2)), toScale) + ...
besseli( -2 + (2*kappa*theta)/Power(sigma,2), ...
(4*Power(E,(Delta*kappa)/2.)*kappa*sqrt(Vs*Vt))/((-1 + Power(E,Delta*kappa))*Power(sigma,2)), toScale)))/ ...
Power(-1 + Power(E,Delta*kappa),2) + Power(sigma,4)* ...
besseli( -1 + (2*kappa*theta)/Power(sigma,2), (4*Power(E,(Delta*kappa)/2.)*kappa*sqrt(Vs*Vt))/ ...
((-1 + Power(E,Delta*kappa))*Power(sigma,2)),toScale) + ...
(Power(E,(Delta*kappa)/2.)*kappa*((1 - Power(E,Delta*kappa))* ...
(-4 + 2*Delta*kappa + Power(Delta,2)*Power(kappa,2) + ...
Power(E,2*Delta*kappa)*(-4 - 2*Delta*kappa + Power(Delta,2)*Power(kappa,2)) + ...
Power(E,Delta*kappa)*(8 + 6*Power(Delta,2)*Power(kappa,2)))*Power(sigma,2)*sqrt(Vs*Vt)* ...
(besseli((2*kappa*theta)/Power(sigma,2), (4*Power(E,(Delta*kappa)/2.)*kappa*sqrt(Vs*Vt))/ ...
((-1 + Power(E,Delta*kappa))*Power(sigma,2)), toScale) + ...
besseli(-2 + (2*kappa*theta)/Power(sigma,2),  ...
(4*Power(E,(Delta*kappa)/2.)*kappa*sqrt(Vs*Vt))/((-1 + Power(E,Delta*kappa))*Power(sigma,2)), toScale)) -  ...
2*Power(E,(Delta*kappa)/2.)*kappa*Power(2 + Delta*kappa + Power(E,Delta*kappa)*(-2 + Delta*kappa),2)*Vs*Vt* ...
(besseli(-3 + (2*kappa*theta)/Power(sigma,2),  ...
(4*Power(E,(Delta*kappa)/2.)*kappa*sqrt(Vs*Vt))/((-1 + Power(E,Delta*kappa))*Power(sigma,2)), toScale) + ...
2*besseli(  -1 + (2*kappa*theta)/Power(sigma,2),...
(4*Power(E,(Delta*kappa)/2.)*kappa*sqrt(Vs*Vt))/((-1 + Power(E,Delta*kappa))*Power(sigma,2)), toScale) + ...
besseli(1 + (2*kappa*theta)/Power(sigma,2),  ...
(4*Power(E,(Delta*kappa)/2.)*kappa*sqrt(Vs*Vt))/((-1 + Power(E,Delta*kappa))*Power(sigma,2)), toScale))))/ ...
(2.*Power(-1 + Power(E,Delta*kappa),4))))/ ...
((kappa - kappa/Power(E,Delta*kappa))*besseli( -1 + (2*kappa*theta)/Power(sigma,2), ...
(4*Power(E,(Delta*kappa)/2.)*kappa*sqrt(Vs*Vt))/((-1 + Power(E,Delta*kappa))*Power(sigma,2)), toScale)))/(4.*Power(kappa,3)); 
