function skewUn = skewUnBates(t, lambda, muj, vj, kappa, theta, sigma, rho)
skewUn = (sigma*(-6*(sigma^3) + kappa*(sigma^2)*(36*rho - 3*sigma*t) + (kappa^3)*rho*(24 - ...
    24*rho*sigma*t) + (kappa^2)*sigma*(-12 - 48*(rho^2) + 18*rho*sigma*t))*theta - exp(kappa*t)*...
    (-6*(sigma^4)*theta - 24*(kappa^4)*rho*sigma*t*theta + kappa*(sigma^3)*(36*rho + ...
    3*sigma*t)*theta + (kappa^2)*(sigma^2)*(-12 - 48*(rho^2) - 18*rho*sigma*t)*theta + ...
    (kappa^3)*sigma*(12*sigma*t + rho*(24 + 24*rho*sigma*t))*theta + (kappa^5)*lambda*t*(vj^2)*...
    (12 + vj) + (kappa^5)*lambda*t*log(1 + muj)*((-24 - 6*vj)*vj + 12*vj*log(1 + muj) - ...
    8*(log(1 + muj)^2))))/(exp(kappa*t)*(kappa^5)*(((-1 + exp(-(kappa*t)))*(sigma^2)*theta - ...
    4*(kappa^2)*rho*sigma*t*theta + kappa*sigma*((4 - 4/exp(kappa*t))*rho + sigma*t)*theta + ...
    (kappa^3)*t*(4*theta + lambda*vj*(4 + vj)))/(kappa^3) - 4*lambda*t*vj*log(1 + muj) + ...
    4*lambda*t*(log(1 + muj)^2))^1.5);