function x =  skewCdist(gamma1, kappa, theta, sigma, rho, t, v0)
  
  
ekt = exp(kappa .* t);
e2kt = ekt.^2;
g1m1 = gamma1 - 1;
k2 = kappa.^2;
k3 = kappa.^3;
s2 = sigma.^2;
s3 = sigma.^3;
r2 = rho.^2;
tm2v = theta - 2 .* v0;
tm3v = theta - 3 .* v0;
kt = kappa .* t;
st = sigma .* t;
ektm1 = ekt - 1;
  
  x = (sqrt(2).*(-((ektm1.*k3.*sigma.*(2..*rho + g1m1.*(-2.*kappa.*rho + sigma).*t).* ...
                 (g1m1.*t.*(-(e2kt.*(12.*kappa - g1m1.*s2.*t).*theta) + ekt.*(-(g1m1.*s2.*t.*(2.*theta - 3..*v0)) + 12.*kappa.*tm2v) + g1m1.*s2.*t.*tm3v) - ...
                    4.*ektm1.*g1m1.*rho.*st.*(-1 + g1m1.*kt).*(ektm1.*theta + 3.*v0) + ...
                    4.*r2.*(e2kt.*(1 + g1m1.*kt.*(1 + g1m1.*kt)).*theta + (1 + kappa.*(t - gamma1.*t)).^2.*tm3v + ...
                            ekt.*((-2 - g1m1.*kt.*(-1 + 2.*g1m1.*kt)).*theta + 3.*(1 + g1m1.^2.*k2.*t.^2).*v0))))./ ...
                ((-4.*g1m1.*rho.*t.*(2.*rho + g1m1.*st).*tm2v + 8.*ekt.*g1m1.*t.*(1 + r2 + g1m1.*rho.*st).*(theta - v0) +  ...
                    4.*ektm1.*g1m1.^2.*kappa.*r2.*t.^2.*(ektm1.*theta + 2.*v0) + (ektm1.*(2.*rho + g1m1.*st).^2.*(ektm1.*theta + 2.*v0))/kappa - ...
                    4.*e2kt.*t.*(g1m1.*(2 + g1m1.*rho.*st).*theta + 2.*gamma1.*(-1 + r2).*v0))/e2kt).^1.5) - ...
              (sigma.*(s3.*tm3v + 3.*e2kt.*((-16.*k3.*rho.*(2 + kt) - 8.*kappa.*rho.*s2.*(2 + kt).^2 + s3.*(5 + 2.*kt.*(3 + kt)) + ...
                                           8.*k2.*sigma.*(2 + 2.*kt + r2.*(6 + kt.*(4 + kt)))).*theta + ...
                                          (16.*k3.*rho.*(1 + kt) + 8.*k2.*rho.*s2.*t.*(2 + kt) + s3.*(1 - 2.*kt.*(1 + kt)) - 8.*k2.*sigma.*(2.*kt + r2.*(2 + kt.*(2 + kt)))).*v0) + ...
                        6.*ekt.*sigma.*(-2.*k2.*(-1 + rho.*st).*tm2v + s2.*(theta - v0) + kappa.*sigma.*(st.*tm2v + rho.*(-4.*theta + 6.*v0))) + ...
                        2.*exp(3 .* kappa .* t).*(-24.*kappa.^4.*rho.*t.*theta + s3.*(-11.*theta + 3.*v0) + 3.*kappa.*s2.*(20.*rho.*theta + st.*theta - 6.*rho.*v0) + ...
                                                12.*k3.*(4.*rho.*theta + st.*theta + 2.*r2.*st.*theta - 2.*rho.*v0) - 6.*k2.*sigma.*((5 + 3.*rho.*(4.*rho + st)).*theta - 2.*(v0 + 2.*r2.*v0)))))./ ...
                            ((s2.*tm2v + e2kt.*(8.*k3.*t.*theta - 8.*k2.*(theta + rho.*st.*theta - v0) + s2.*(-5.*theta + 2.*v0) + 2.*kappa.*sigma.*(8.*rho.*theta + st.*theta - 4.*rho.*v0)) + ...
                  4.*ekt.*(s2.*theta - 2.*k2.*(-1 + rho.*st).*(theta - v0) + kappa.*sigma.*(st.*(theta - v0) + 2.*rho.*(-2.*theta + v0))))/(e2kt.*k3)).^1.5 ...
  ))/(exp(3 .* kappa .* t).*kappa.^5);
  
end